services:
  questdb:
    image: questdb/questdb:7.3.9
    hostname: questdb
    container_name: questdb
    ports:
      - "9000:9000"
      - "9009:9009"
    restart: unless-stopped
    environment:
      - QDB_PG_READONLY_USER_ENABLED=true
    volumes:
      - questdb-storage:/var/lib/questdb
volumes:
  questdb-storage: {}
